# Copyright (c) 2020, NVIDIA CORPORATION.

{% set version = environ.get('RAPIDS_VERSION', '0.0.0.dev') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set build_offset = environ.get('RAPIDS_OFFSET', 0) %}
{% set cuda_version = '.'.join(environ.get('CUDA_VERSION', '9.2').split('.')[:2]) %}
{% set py_version = environ.get('CONDA_PY', 36) %}

package:
  name: rapids-notebook-env
  version: {{ version }}

source:
  path: .

build:
  number: {{ build_offset }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ build_offset }}
  script_env:
    - RAPIDS_VERSION
    - RAPIDS_OFFSET
    - CUDA_VERSION

requirements:
  host:
    - python
  run:
    - conda-forge::blas=2.14=openblas
    - cudatoolkit ={{ cuda_version }}.*
    - cupy >=6.6.0,<8.0.0a0,!=7.1.0
    - cython >=0.29,<0.30
    - dask-labextension
    - dask-ml
    - ipython =7.3.*
    - jupyterlab =1.2.0
    - matplotlib
    - networkx
    - nodejs
    - pytest
    - scikit-learn =0.21.3
    - scipy =1.3.0
    - seaborn
    - umap-learn

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: 'RAPIDS Notebook Dependencies and Tool Environment Installer'
  description: |
    Meta-package for installing notebook dependencies and tools needed to run RAPIDS notebooks.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/
