# Copyright (c) 2020, NVIDIA CORPORATION.

{% set version = environ.get('RAPIDS_VER', '0.0.0.dev') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set build_offset = environ.get('RAPIDS_OFFSET', 0) %}
{% set cuda_version = '.'.join(environ.get('CUDA_VERSION', '10.0').split('.')[:2]) %}
{% set py_version = environ.get('CONDA_PY', 36) %}

### 
# Versions referenced below are set in `conda/recipe/*versions.yaml` except for
#   those set above (e.g. `cuda_version`)
#
# gpuCI loads the correct file based on the build type (NIGHTLY or RELEASE) in 
#   `ci/cpu/build.sh` and `ci/axis/*.yaml`
#
# Manual builds need to use the `conda build` flag of `-m <path-to-file>.yaml` 
#   to set these versions
###

package:
  name: rapids-notebook-env
  version: {{ version }}

source:
  path: .

build:
  number: {{ build_offset }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ build_offset }}
  script_env:
    - RAPIDS_VER
    - RAPIDS_OFFSET
    - CUDA_VERSION

requirements:
  host:
    - python
  run:
    - bokeh {{ bokeh_version }}
    - conda-forge::blas{{ blas_version }}
    - cudatoolkit ={{ cuda_version }}.*
    - cupy {{ cupy_version }}
    - cython {{ cython_version }}
    - dask-labextension
    - dask-ml
    - ipython {{ ipython_version }}
    - jupyterlab {{ jupyterlab_version }}
    - matplotlib
    - networkx
    - nodejs {{ nodejs_version }}
    - pytest
    - scikit-learn {{ scikit_learn_version }}
    - scipy {{ scipy_version }}
    - seaborn
    - umap-learn

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: 'RAPIDS Notebook Dependencies and Tool Environment Installer'
  description: |
    Meta-package for installing notebook dependencies and tools needed to run RAPIDS notebooks.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/
