# Copyright (c) 2019, NVIDIA CORPORATION.

{% set version = environ.get('RAPIDS_VERSION', '0.0.0.dev') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set build_offset = environ.get('RAPIDS_OFFSET', 0) %}
{% set cuda_version = '.'.join(environ.get('CUDA_VERSION', '9.2').split('.')[:2]) %}
{% set py_version = environ.get('CONDA_PY', 36) %}
{% set xgb_version = environ.get('XGBOOST_VERSION', '1.0.0.SNAPSHOT') %}
{% set dxgb_version = environ.get('DASK_XGBOOST_VERSION', '0.2.0.dev28') %}

package:
  name: rapids-xgboost
  version: {{ version }}

source:
  path: .

build:
  number: {{ build_offset }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ build_offset }}
  script_env:
    - RAPIDS_VERSION
    - RAPIDS_OFFSET
    - CUDA_VERSION
    - XGBOOST_VERSION
    - DASK_XGBOOST_VERSION

requirements:
  host:
    - python x.x
  run:
    - cudatoolkit ={{ cuda_version }}.*
    - nccl =2.4.*
    - python x.x
    - dask-xgboost ={{ dxgb_version }}
    - xgboost ={{ xgb_version }}

about:
  home: http://rapids.ai/
  license: Custom
  license_file: LICENSE
  summary: 'RAPIDS + DMLC XGBoost & Dask Integration'
  description: |
    Meta-package for RAPIDS + DMLC XGBoost & Dask integration; version matched for RAPIDS releases.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/xgboost
