# Copyright (c) 2019, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set build_offset = environ.get('RAPIDS_OFFSET', 0) %}
{% set cuda_version = '.'.join(environ.get('CUDA_VERSION', '10.0').split('.')[:2]) %}
{% set py_version = environ.get('CONDA_PY', 36) %}

### 
# Versions referenced below are set in `conda/recipe/*versions.yaml` except for
#   those set above (e.g. `cuda_version`)
#
# gpuCI loads the correct file based on the build type (NIGHTLY or RELEASE) in 
#   `ci/cpu/build.sh` and `ci/axis/*.yaml`
#
# Manual builds need to use the `conda build` flag of `-m <path-to-file>.yaml` 
#   to set these versions
###

package:
  name: rapids-xgboost
  version: {{ version }}

source:
  path: .

build:
  number: {{ build_offset }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ build_offset }}
  script_env:
    - RAPIDS_VER
    - RAPIDS_OFFSET
    - CUDA_VERSION
    - VERSION_SUFFIX

requirements:
  host:
    - python
  run:
    - cudatoolkit ={{ cuda_version }}.*
    - nccl {{ nccl_version }}
    - python
    - xgboost {{ xgboost_version }}

about:
  home: http://rapids.ai/
  license: Custom
  license_file: LICENSE
  summary: 'RAPIDS + DMLC XGBoost Integration'
  description: |
    Meta-package for RAPIDS + DMLC XGBoost integration; version matched for RAPIDS releases.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/xgboost
