# Copyright (c) 2019, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '9.2').split('.')[:2]) %}
{% set py_version=environ.get('CONDA_PY', 36) %}
{% set xgb_version=environ.get('XGBOOST_VERSION', '1.0.0.SNAPSHOT') %}
{% set dxgb_version=environ.get('DASK_XGBOOST_VERSION', '0.2.0.dev28') %}

package:
  name: rapids-xgboost
  version: {{ version }}

source:
  path: .

build:
  number: {{ git_revision_count }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ git_revision_count }}
  script_env:
    - VERSION_SUFFIX
    - CUDA_VERSION
    - XGBOOST_VERSION
    - DASK_XGBOOST_VERSION

requirements:
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - nccl=2.4.*
    - python x.x
    - dask-xgboost={{ dxgb_version }}.*
    - xgboost={{ xgb_version }}.*

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'RAPIDS + DMLC XGBoost & Dask Integration'
  description: |
    Meta-package for RAPIDS + DMLC XGBoost & Dask integration; version matched for RAPIDS releases.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/xgboost
