# Copyright (c) 2019, NVIDIA CORPORATION.

{% set version = environ.get('RAPIDS_VERSION', '0.0.0.dev') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set build_offset = environ.get('RAPIDS_OFFSET', 0) %}
{% set cuda_version = '.'.join(environ.get('CUDA_VERSION', '9.2').split('.')[:2]) %}
{% set py_version = environ.get('CONDA_PY', 36) %}

package:
  name: rapids
  version: {{ version }}

source:
  path: .

build:
  number: {{ build_offset }}
  string: cuda{{ cuda_version }}_py{{ py_version }}_{{ build_offset }}
  script_env:
    - RAPIDS_VERSION
    - RAPIDS_OFFSET
    - CUDA_VERSION

requirements:
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - nccl=2.4.*
    - numba=0.45.1
    - numpy=1.16.4 #TODO-verfiy this version
    - python x.x
    - cudf={{ minor_version }}.*
    - cugraph={{ minor_version }}.*
    - cuml={{ minor_version }}.*
    - cuspatial={{ minor_version }}.*
    - dask-cuda={{ minor_version }}.*
    - nvstrings={{ minor_version }}.*
    - rapids-xgboost={{ minor_version }}.*
    - rmm={{ minor_version }}.*

test:
  imports:
    - rmm
    - nvstrings
    - nvtext
    - nvcategory
    - cudf
    - dask_cudf
    - streamz
    - cuml
    - cugraph
    - cuspatial

about:
  home: http://rapids.ai/
  license: Custom
  license_file: LICENSE
  summary: 'RAPIDS Suite - Open GPU Data Science'
  description: |
    Meta-package for the RAPIDS suite of software libraries gives you the freedom to execute end-to-end data science 
    and analytics pipelines entirely on GPUs. It relies on NVIDIA® CUDA® primitives for low-level compute optimization, 
    but exposes that GPU parallelism and high-bandwidth memory speed through user-friendly Python interfaces.
  doc_url: https://docs.rapids.ai/
  dev_url: https://github.com/rapidsai/
